SRC = strlene.c
SRC2 = strcaat.c
SRC3 = strcmpp.c
SRC4 = strstrr.c
SRC5 = strchrr.c
SRC6 = strcpyy.c

TGT:= strlen
TGT2:= strcat
TGT3:= strcmp
TGT4:= strstr
TGT5:= strchr
TGT6:= strcpy


all:
	gcc $(SRC) -o $(TGT)
	gcc $(SRC6) -o $(TGT6)
	gcc $(SRC2) -o $(TGT2)
	gcc $(SRC3) -o $(TGT3)
	gcc $(SRC4) -o $(TGT4)
	gcc $(SRC5) -o $(TGT5)	

clean:
	rm -rf $(TGT) $(TGT2) $(TGT3) $(TGT4) $(TGT5) $(TGT6)
	
